services:
  backend:
    build:
      target: builder 
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "9229:9229"  

  frontend:
    volumes:
      - ./frontend:/usr/share/nginx/html
    
  db:
    ports:
      - "5432:5432"  